steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/secret-epsilon-347314/first_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/secret-epsilon-347314/first_app']